# Generated by Django 5.2.7 on 2025-10-30 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=35)),
                ('bio', models.TextField(null=True)),
                ('profile_image', models.ImageField(null=True, upload_to='profile/')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('latest_update', models.DateField(auto_now=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
