# Generated by Django 5.2.7 on 2025-11-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
